### ISSUE TITLE
Angular degree search: don't display subplan `<ul>` if no subplans are available

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-Search-Plugin#104]
**Describe the bug**

In the angular degree search results list, all degrees have a `<ul>` rendered on the page for storing a nested list of subplans, regardless of whether the degree has subplans or not.

We get flagged for this in accessibility scans when those `<ul>`s are empty (a degree has no subplans) because `<ul>`s have the implicit `role="list"`, and thus _must_ contain at least one `listitem` element.

https://github.com/UCF/UCF-Degree-Search-Plugin/blob/82ec36c6d5960fc6565c36f3d1e3174902b2d99a/includes/ucf-degree-search-angular-common.php#L193-L199

**Steps to Reproduce**

n/a; see SiteImprove

**Expected Behavior**

The `<ul>` that contains a degree's list of subplans should only be rendered on the page if at least one subplan is available to display.

**Possible Fix**

Remove/adjust `ng-repeat` repeat in the snippet above.

**Your environment:**

n/a

**Additional context**

n/a

**Comment by rjucf** [comment]
Resolved with #105
