### ISSUE TITLE
Enqueue plugin assets outside of UCF_Degree_Search_Common::display_degree_search()

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-Search-Plugin#11]
Plugin styles and scripts need to be enqueued outside of this function (and always be enqueued, regardless of whether or not a degree search is displayed on the page), due to styles and scripts getting enqueued too late during execution. It being called so late will result in inconsistent enqueuing results over https vs http due to timing differences.

Related:
https://github.com/UCF/Online-Theme/pull/29

Similar issue on the Events plugin:
https://github.com/UCF/UCF-Events-Plugin/issues/1

**Comment by jmbarne3** [comment]
Solved in #12
