### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-Search-Plugin#20]
Ideally we should keep the accessibility features of the current degree search:
- Update assistive text using wp.a11y when results are updated/filters are changed (e.g. announce "<RESULT COUNT> results found in <FILTERS> at UCF"):  https://github.com/UCF/Main-Site-Theme/blob/master/src/js/script.js#L798-L799
- Announce when an error occured:  https://github.com/UCF/Main-Site-Theme/blob/master/src/js/script.js#L821-L822

**Comment by jmbarne3** [comment]
Closed by #31
