### ISSUE TITLE
Mobile filters

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-Search-Plugin#22]
Shifting the available filters up to the top of the page for mobile users would be ideal.  In the current degree search, we hide them behind a toggleable modal:

![screen shot 2017-06-16 at 9 14 21 am](https://user-images.githubusercontent.com/1649216/27230254-3f02ef1a-5274-11e7-9d86-88e5a311a763.png)

![screen shot 2017-06-16 at 9 14 36 am](https://user-images.githubusercontent.com/1649216/27230265-434894b2-5274-11e7-9274-ca2ea0579fbf.png)

**Comment by jmbarne3** [comment]
Fixed in #38
