### ISSUE TITLE
Angular search: program type and college filters disappear after searching for terms with no results

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-Search-Plugin#27]
Steps to re-create:

- Navigate to a page with the Angular degree search implemented (e.g. main site v3 degree search page) with no search terms or filters pre-selected
- Search for any garbage search term that won't return any results
- The no results message will be returned, and the program type and college filters lists will disappear
- Wipe out the search term; program types will re-appear but colleges may not... on my local WP instance, they re-appear, but in Dev, they do not

Behavior is consistent in latest Chrome, FF and Safari.  Haven't tested in Edge or IE.

**Comment by jmbarne3** [comment]
Closed by #31
