### ISSUE TITLE
"Default number of typeahead results" option defaults to 0 instead of 5

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-Search-Plugin#55]
This option should be defaulting to a value of 5, but on a fresh plugin installation, I'm seeing 0.

https://github.com/UCF/UCF-Degree-Search-Plugin/blob/master/admin/ucf-degree-search-config.php#L12

**Comment by jmbarne3** [comment]
Resolved in v0.6.0 #56.
