### ISSUE TITLE
Update default `query_params` value.

### ISSUE THREAD

**Issue by jmbarne3** [UCF/UCF-Degree-Search-Plugin#62]
Currently the default `query_params` value is set to `%q` which will not actually work. For example, if a user searches for "History", the resulting request, using the default values, would be `https://www.ucf.edu/online/wp-json/wp/v2/degrees/History`, which should return a 404. Instead the default should be `?search=%q`.

**Comment by cadieb** [comment]
Resolved in v0.7.1
