### ISSUE TITLE
Update comments for UCF_Degree_Search_Feed::get_degrees() return value

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-Search-Plugin#70]
`UCF_Degree_Search_Feed::get_degrees()` is expected to return an object, not an array, when used with the expected feed URL (the UCF Degree Search plugin's angular API URL base).  Function comments noting that this function returns an array should be updated.

See:

- https://github.com/UCF/UCF-Degree-Search-Plugin/blob/master/includes/ucf-degree-search-feed.php#L13
- https://github.com/UCF/UCF-Degree-Search-Plugin/blob/master/includes/ucf-degree-external-list-common.php#L11

**Comment by cadieb** [comment]
Resolved in v0.7.1
