### ISSUE TITLE
Update Script Handles

### ISSUE THREAD

**Issue by jmbarne3** [UCF/UCF-Degree-Search-Plugin#83]
Update the scripts handles for typeahead and handlebars to use more generic names like `typeahead-js` and `handlebars-js`. This will allow for common name handling between plugins, making it possible to check to see if it's enqueued by another plugin before enqueuing. 

https://github.com/UCF/UCF-Degree-Search-Plugin/blob/master/includes/ucf-degree-search-common.php#L166-L167

**Comment by cjg89** [comment]
Resolved in v0.7.7.
